// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class HWHelloWorld;


/** http://mobilecpptutorials.com/your-first-cross-platform-djinni-app-part-1-cplusplus/ */
@interface HWHelloWorld : NSObject

+ (nullable HWHelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

@end
